# Generated by Django 5.0.3 on 2024-04-26 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diplomapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="specialistprofile",
            name="about",
            field=models.TextField(
                default="About", max_length=300, verbose_name="О себе"
            ),
        ),
        migrations.AlterField(
            model_name="specialistprofile",
            name="city",
            field=models.CharField(
                default="City", max_length=128, verbose_name="Город"
            ),
        ),
        migrations.AlterField(
            model_name="specialistprofile",
            name="firstname",
            field=models.CharField(default="Name", max_length=50, verbose_name="Имя"),
        ),
        migrations.AlterField(
            model_name="specialistprofile",
            name="lastname",
            field=models.CharField(
                default="Surname", max_length=50, verbose_name="Фамилия"
            ),
        ),
        migrations.AlterField(
            model_name="specialistprofile",
            name="patronimic",
            field=models.CharField(
                default="Patronimic", max_length=128, null=True, verbose_name="Отчество"
            ),
        ),
        migrations.AlterField(
            model_name="specialistprofile",
            name="phonenumber",
            field=models.CharField(
                default=1, max_length=16, verbose_name="Номер телефона"
            ),
        ),
        migrations.AlterField(
            model_name="specialistprofile",
            name="reviews",
            field=models.TextField(
                default="Reviews", max_length=300, verbose_name="Отзывы"
            ),
        ),
    ]
